### ISSUE TITLE
Question: Why using a NEW folder instead of creating a development branch?

### ISSUE THREAD

**Issue by SimplyCEO** [prismz/aurinstall#1]
The repository would look better and also developers would have a point where to start.
Like me, I have no idea if I should open a commit for root or NEW.

For me a more concise way is to move all the contents of NEW to a `dev` branch, lock `master`, and open a PR to merge `dev` to `master`.
This way people can track the update while knowing where to contribute.

I want to help on the development.

**Comment by prismz** [comment]
Apologies for the late response. This is my first fully fledged program I've written and I'm not exactly proficient with git or GitHub, honestly didn't expect anyone to want to contribute lol. Will make suggested changes

**Comment by SimplyCEO** [comment]
Great! I will take a look into it and see if I can help with something.
